In [2]:
import numpy as np

In [95]:
a = np.array([1,2,3,4,5])
e = np.array([6,7,8,9,10])
print(a)
print(e)
out_arr = np.column_stack((a,e))
print(out_arr)
print(type(a))
print(a.shape)

[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
<class 'numpy.ndarray'>
(5,)


In [4]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [5]:
b[3][0]

4

In [6]:
# Create Zeroes,Ones,Custom array
a = np.zeros((3,3))
print(a)

b = np.ones((3,4))
print(b)

#Array of some constants
c = np.full((3,2),5)
print(c)

#Identity Matrix - Size/Square Matrix
d = np.eye(4)
print(d)

#Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.46807575 0.0067384  0.124818  ]
 [0.8869838  0.24496152 0.25544244]]


In [7]:
print(randomMatrix[:,2])

[0.124818   0.25544244]


In [8]:
randomMatrix[1,1:] = 1
print(randomMatrix)

[[0.46807575 0.0067384  0.124818  ]
 [0.8869838  1.         1.        ]]


In [47]:
z = np.zeros((3,3),dtype = np.int64)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
z = np.zeros((3,3),dtype = np.int64)
z[:3,0] = 7
#z[1,:] = 5
print(z)

[[7 0 0]
 [7 0 0]
 [7 0 0]]


In [10]:
#Datatype
print(z.dtype)

int64


In [11]:
# Mathematical Operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
# Element wise Addition
print(x+y)
print(np.add(x,y))
print(np.sub(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [12]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [13]:
# Matrix Multiplication/Dot Product
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [26]:
# Multi. of Vectors
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [27]:
print(x)

[[1 2]
 [3 4]]


In [28]:
print(np.sum(x ,axis=0))  # axis = 0 ---->
# axis = 1 |
#          |
#          |
#          ~

[4 6]


In [29]:
#Stacking Of Arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [30]:
a = np.stack((a,b),axis=0)


In [37]:
#Reshape Of Nupy array
a = a.reshape((-1,4))
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [43]:
#Numpy Random Module
a = np.arange(10)

In [44]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[2 9 6 4 0 3 1 7 8 5]


In [45]:
# Returns values from a standard Normal Distribution
a = np.random.rand(2,4)
print(a)
a = np.random.randint(2,4,3)
print(a)
element = np.random.choice([1,4,3,2,11,27])
print(element)

[[0.38791074 0.66974604 0.93553907 0.84631092]
 [0.31327352 0.52454816 0.44345289 0.22957721]]
[2 2 2]
4


In [63]:
#Numpy - Statistics

In [67]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
# Specify axis for the direction in case of multi array
print(np.min(a))
print(np.min(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
1
[1 5]


In [69]:
b = np.array([1,2,3,4])
n = sum(b)/4
print(n)

print(np.mean(b))

2.5
2.5


In [73]:
#Median
c = np.array([1,3,4,2,0])
print(np.median(c))

2.0


In [74]:
#Mean vs. Average is weighted
print(np.mean(c))

2.0


In [76]:
w = np.array([1,2,3,4,9])
print(np.average(c,weights=w))

1.4210526315789473


In [77]:
#Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)



1.4142135623730951


In [80]:
for i in range(5):
    a = np.array([i])
print(a)

[4]


In [82]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:
d = np.flatten('F')
print(d.shape)

AttributeError: module 'numpy' has no attribute 'flatten'

In [98]:
f = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(f)
print(f.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
